### ISSUE TITLE
[Bug]: linting problem

### ISSUE THREAD

**Issue by Temepest74** [kiwilan/typescriptable-laravel#36]
### What happened?

I have problems with this line:
```
/* eslint-disable eslint-comments/no-unlimited-disable */
```
and when i run my linter I get
```

/var/www/html/resources/js/types/models.d.ts
  1:1  error  Definition for rule 'eslint-comments/no-unlimited-disable' was not found  eslint-comments/no-unlimited-disable

✖ 1 problem (1 error, 0 warnings)
```

If I do what is on [this](https://mysticatea.github.io/eslint-plugin-eslint-comments/) page I get
```
/var/www/html/resources/js/types/models.d.ts
  1:19  error  Requires 'eslint-enable' directive for 'eslint-comments/no-unlimited-disable'  eslint-comments/disable-enable-pair
  2:0   error  Requires 'eslint-enable' directive                                             eslint-comments/disable-enable-pair

```

### How to reproduce the bug

Just install the package

### Package Version

latest

### PHP Version

8.1.0

### Which operating systems does with happen with?

Windows

**Comment by ewilan-riviere** [comment]
Can you check if it is fixed with latest version?

**Comment by Temepest74** [comment]
yest, thank you

**Comment by joelstein** [comment]
I'm still having this issue. Did you intend to include `/* eslint-disable eslint-comments/no-unlimited-disable */` in the following files?

- routes.ts
- types-eloquent.d.ts
- types-routes.d.ts
