### ISSUE TITLE
[Bug]: Generating models error when using DB_PREFIX

### ISSUE THREAD

**Issue by ngekoding** [kiwilan/typescriptable-laravel#44]
### What happened?

Just using prefix for my databases tables by setting in the `config/database.php` (e.g. `sv_`).

Then, when trying to run the command:
```sh
php artisan typescriptable:models
```

I get this errors:
```sh
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'survey.responses' doesn't exist (Connection: mysql, SQL: SHOW COLUMNS FROM responses)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:822
    818▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    819▕                 );
    820▕             }
    821▕ 
  ➜ 822▕             throw new QueryException(
    823▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    824▕             );
    825▕         }
    826▕     }

  i   A table was not found: You might have forgotten to run your database migrations. 
      https://laravel.com/docs/master/migrations#running-migrations

      +27 vendor frames 

  28  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

### How to reproduce the bug

1. Setting the database prefix
2. Install the package
3. Try to generate TS types for models
4. Error table not found!

### Package Version

^1.11

### PHP Version

8.2.10

### Which operating systems does with happen with?

macOS

### Notes

I was try to publish the package configuration and I don't found any related config to settings the database tables prefix.

**Comment by ewilan-riviere** [comment]
Thanks, I will fix this today!

**Comment by ngekoding** [comment]
@ewilan-riviere Thank you

**Comment by ewilan-riviere** [comment]
Can you test latest release? ;)

**Comment by ngekoding** [comment]
<img width="381" alt="Screen Shot 2024-01-10 at 16 26 39" src="https://github.com/kiwilan/typescriptable-laravel/assets/11625690/0e72190f-5031-4a36-bde6-f523fa04df04">

**Solved!** Thank you.
