### ISSUE TITLE
[Bug]: Missing model columns

### ISSUE THREAD

**Issue by ngekoding** [kiwilan/typescriptable-laravel#46]
### What happened?

The generated types only include some table columns.

Let's say we have this users table columns:

<img width="385" alt="Screen Shot 2024-01-10 at 16 45 31" src="https://github.com/kiwilan/typescriptable-laravel/assets/11625690/bb4a21f1-9f69-4dad-adf8-cec1dbd6c868">

User's model:

```php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory;
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    /**
     * Get the user's responses.
     */
    public function responses(): HasMany
    {
        return $this->hasMany(Response::class);
    }
}
```
And it is what we get:

<img width="522" alt="Screen Shot 2024-01-10 at 16 46 53" src="https://github.com/kiwilan/typescriptable-laravel/assets/11625690/8e16dffa-e204-44dd-a25c-9c0ab617d76d">

### How to reproduce the bug

1. Just generate TS types for models
2. Generated type only contains some columns

### Package Version

^1.11.33

### PHP Version

8.2.10

### Which operating systems does with happen with?

macOS

**Comment by ewilan-riviere** [comment]
Strange bug, I will try to reproduce it, thanks 👍

**Comment by ewilan-riviere** [comment]
@ngekoding I try to reproduce your problem, but I can't, can you provide a repository like this one?

https://github.com/ewilan-riviere/laravel-typescriptable-test

**Comment by ngekoding** [comment]
Of course, here is the repository: https://github.com/ngekoding/laravel-typescriptable-test

**Comment by ewilan-riviere** [comment]
Thanks, I will fix this soon!

**Comment by ewilan-riviere** [comment]
Can you try latest release?

**Comment by ngekoding** [comment]
<img width="491" alt="Screen Shot 2024-01-12 at 06 02 36" src="https://github.com/kiwilan/typescriptable-laravel/assets/11625690/d3b92574-edcf-4dfd-8930-e6e4ede8835a">

It seems to have **worked** now.

**Comment by ngekoding** [comment]
Sorry maybe it is a different thing, but as for now I just thinking about the `Date` type like for `created_at`, how can we cast it to JavaScript `Date` as we get `string` from the server and passed directly as component props?

Like we have this page component:

```vue
// Pages/User/UserList.vue
<script setup lang="ts">
definesProps<{
  users: App.User[]
}>
</script>

<template>
  <ul>
    <li v-for="user in users">The user <b>{{ user.name }}<b> was created on {{ user.created_at }}.</li>
  </ul>
</template>
```

And in the server we have:

```php
$users = User::all();

return Inertia::render('User/UserList', [
   'users' => $users
]);
```

**Comment by ewilan-riviere** [comment]
Thanks, I will fix this soon!

**Comment by ewilan-riviere** [comment]
Can you try with latest release?

**Comment by ngekoding** [comment]
Sorry, will try it as soon as possible.

**Comment by ngekoding** [comment]
**Solved!**

<img width="486" alt="Screen Shot 2024-01-16 at 08 13 24" src="https://github.com/kiwilan/typescriptable-laravel/assets/11625690/7ab0d5c4-d724-44ed-80cd-0ef9597b4824">
