### ISSUE TITLE
[Bug]: Can't generate types when using base model class

### ISSUE THREAD

**Issue by PerryRylance** [kiwilan/typescriptable-laravel#89]
### What happened?

Hello folks

I appreciate I may need to raise this elsewhere considering `artisan` is one of the parsers, but the behaviour is the same when I switch to `parser`.

A common pattern for me is to make a base model class for my app then inherit other models from this. When I do this, this package doesn't identify my models.

### How to reproduce the bug

- Fresh install
- Make a base class `App\Models\Model` extending `Illuminate\Database\Eloquent\Model`
- Make a model `App\Models\Example` extending `App\Models\Model`
- Run `artisan typescriptable`

Expected
- Type for `Example`

Observed
- Types for `User` and the base `Model` but not `Example`

### Package Version

3.1

### PHP Version

8.4

### Which operating systems does with happen with?

Linux

### Notes

Laravel 11

**Comment by PerryRylance** [comment]
I tried to open a pull request for this but couldn't.

I changed `SchemaClass` near line 62 to this:

`$parser->isModel = $reflect->isSubclassOf('Illuminate\Database\Eloquent\Model');`

This solved the issue for me.

Could this change be made please?

**Comment by PerryRylance** [comment]
Seeing the expected behaviour after applying this change and switching the engine back to `artisan`

**Comment by ewilan-riviere** [comment]
Thanks for this bugfix, I will publish it today!

**Comment by ewilan-riviere** [comment]
Can you test with [v3.1.05](https://github.com/kiwilan/typescriptable-laravel/releases/tag/v3.1.05)?

**Comment by PerryRylance** [comment]
Works as expected, thank you very much!
